services:
  - type: web
    name: mail-promotion-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: SENDER_EMAIL
        sync: false
